site_name: Tour of Heroes
site_description: Tour of Heroes is a sample application that helps a fictional organization manage heroes.
site_author: fvivas.dev
site_url: https://tour-of-heroes.es
repo_url: https://github.com/franvivas/tour-of-heroes-dotnet-api
edit_uri: docs
plugins: 
  - techdocs-core
nav:
  - Home: index.md
  - Management: managing-heroes.md   